name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '_site/'
        destination_repo: 'charliebaldwin/website'
        user_email: 'charlie@charliebaldwin.com'
        user_name: 'charliebaldwin'
        commit_message: 'Copied over new website changes'
